{"remainingRequest":"/Users/scottjoscelyne/Documents/GitHub/oasis/node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js??ref--8-1!/Users/scottjoscelyne/Documents/GitHub/oasis/node_modules/formiojs/node_modules/core-js/internals/call-with-safe-iteration-closing.js","dependencies":[{"path":"/Users/scottjoscelyne/Documents/GitHub/oasis/node_modules/formiojs/node_modules/core-js/internals/call-with-safe-iteration-closing.js","mtime":1594904105381},{"path":"/Users/scottjoscelyne/Documents/GitHub/oasis/node_modules/cache-loader/dist/cjs.js","mtime":1590548237416},{"path":"/Users/scottjoscelyne/Documents/GitHub/oasis/node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js","mtime":1590548235828}],"contextDependencies":[],"result":["var anObject = require('../internals/an-object');\n\n// call something on iterator step with safe closing on error\nmodule.exports = function (iterator, fn, value, ENTRIES) {\n  try {\n    return ENTRIES ? fn(anObject(value)[0], value[1]) : fn(value);\n  // 7.4.6 IteratorClose(iterator, completion)\n  } catch (error) {\n    var returnMethod = iterator['return'];\n    if (returnMethod !== undefined) anObject(returnMethod.call(iterator));\n    throw error;\n  }\n};\n",null]}